version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    hostname: es
    container_name: es
    
    ports:
    - "9200:9200"
    environment:
        discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    hostname: kibana
    container_name: kibana
    
    ports:
    - "5601:5601"
    environment:
        ELASTICSEARCH_HOSTS: http://es:9200
        